---
title: "Codebook"
author: "Freddy Lazcano"
date: "October 31, 2016"
output: html_document
---

# Introduction


The script run_analysis.R performs the 5 steps described in the course project's definition.

* First, all the similar data is merged using the rbind() and cbind() functions.  
* Then, the columns get renamed using the **feature.txt** file, and only the columns with std deviation and mean get extracted from the data set.  
* As activity data is addressed with values 1:6, we take the activity names and IDs from **activity_labels.txt** and they are substituted in the dataset.  
* On the whole dataset, those columns with vague column names are corrected.  
* Finally, we generate a new dataset with all the average measures for each subject and activity type. The output file is called **Cleaning_project.txt**, and uploaded to this repository. 


# Variables

* **x_train**, **y_train**, **x_test**, **y_test**, **subject_train** and **subject_test** contain the data from the downloaded files.
* **features** contain the columns names and **act_lebels** contain the names for each activity
* **test_full**, **train_full** and **All_data** merges all data except the **act_lebels**
* **subset_col** keep only the names of the columns we need to get the tidy data set 
* **All_data_subset** subset the columns in **subset_col**
* **All_data_subset** merge with **act_lebels** to get the activity names